name: Quick Playwright Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install and setup
      run: |
        npm ci
        npx playwright install --with-deps
        
        # Create basic test if none exists
        mkdir -p tests
        if [ ! -f "tests/basic.spec.js" ]; then
          cat > tests/basic.spec.js << 'EOF'
        const { test, expect } = require('@playwright/test');
        test('basic test', async ({ page }) => {
          await page.goto('http://localhost:3000');
          await expect(page).toHaveTitle(/React/);
        });
        EOF
        fi
        
        # Create basic config if none exists  
        if [ ! -f "playwright.config.js" ]; then
          cat > playwright.config.js << 'EOF'
        module.exports = {
          testDir: './tests',
          use: { baseURL: 'http://localhost:3000' },
          webServer: {
            command: 'npm start',
            url: 'http://localhost:3000',
            reuseExistingServer: !process.env.CI,
          },
        };
        EOF
        fi
    
    - name: Run tests
      run: npx playwright test
      
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: report
        path: playwright-report/
        if-no-files-found: ignore